// Stage 5 Task 2 follow-up: an app-level ACL manifest. Without this,
// `tauri-build` never generates any permissions for this crate's own
// `#[tauri::command]`s (only for plugins) — and per Tauri's own IPC
// dispatch (`Webview::on_message`), a *local* invoke of a non-plugin
// command is only ACL-checked at all `if has_app_acl_manifest`. With no
// app manifest, that condition is false, so every app command was
// reachable from *any* window regardless of `capabilities/*.json`'s
// `windows` list — confirmed by reading tauri's own
// `crates/tauri/src/webview/mod.rs` dispatch code. `AppManifest::commands`
// below autogenerates an `allow-$command`/`deny-$command` permission pair
// per listed command (identifiers use hyphens even though the commands
// themselves are snake_case — e.g. `popup_start` becomes
// `allow-popup-start`), written to `./permissions/autogenerated/` (that
// directory is gitignored — see src-tauri/.gitignore — since it's fully
// derived from the list below, the same "generated is not source" treatment
// already given to `/gen/schemas`). `capabilities/default.json` (main
// window) and `capabilities/popup.json` (the meeting-popup window) then
// each opt into only the specific `allow-*` permissions they actually need.
//
// This list must be kept in sync with `lib.rs`'s `tauri::generate_handler!`
// list by hand — there's no compile-time link between the two (a command
// missing from here is simply unreachable from every window once this
// manifest exists at all, which would surface immediately as a broken
// invoke in every affected view, not silently).
const APP_COMMANDS: &[&str] = &[
  "hardware_info",
  "list_models",
  "recommended_models",
  "list_notes",
  "get_note",
  "search_notes",
  "rename_note",
  "toggle_action_item",
  "summarize_note",
  "ask_note",
  "delete_note",
  "storage_stats",
  "reveal_note",
  "get_settings",
  "set_settings",
  "download_model",
  "cancel_download",
  "delete_model",
  "start_recording",
  "pause_recording",
  "resume_recording",
  "stop_recording",
  "popup_start",
  "popup_dismiss",
  "sys_audio_status",
  "request_sys_audio_permission",
];

// Stage 5 Task 4: `ScreenCaptureKit.framework` doesn't exist before macOS
// 12.3 (13.0 for the audio capture `syscap.rs` actually uses), well above
// this crate's declared 11.0 floor (`tauri.conf.json`'s
// `minimumSystemVersion`). `objc2-screen-capture-kit`'s generated bindings
// link it the normal way — a `#[link(name = "ScreenCaptureKit", kind =
// "framework")]` attribute, which rustc/the linker treat exactly like
// `-framework ScreenCaptureKit`: a *hard* `LC_LOAD_DYLIB`. dyld refuses to
// even launch a process whose hard-linked framework is missing — on macOS
// 11/12 that would break the *entire app* at launch, not just gracefully
// report `syscap::SysAudioAvailability::Unsupported` (system-audio's own
// runtime gate; see that module's docs). Passing `-weak_framework` here
// instead makes the linker emit a *weak* `LC_LOAD_WEAK_DYLIB` for the same
// framework, which wins over the dependency's own hard link (confirmed
// empirically: a throwaway binary linking `objc2-screen-capture-kit` both
// with and without this override, inspected via `otool -l`/`otool -L` —
// without it, `ScreenCaptureKit.framework` shows as a plain hard-linked
// dylib; with it, the *same* entry shows `(weak)` / `LC_LOAD_WEAK_DYLIB`,
// with no duplicate hard entry left over). dyld resolves a weak dylib
// lazily and simply leaves it unbound if absent — exactly what a
// runtime-gated feature needs. `syscap.rs` never touches any
// `ScreenCaptureKit` symbol (including class lookups, which fault under
// weak linking if the framework is genuinely missing) unless
// `sys_audio_status` has already reported `Ready`, so this weak link is
// never actually exercised below macOS 13 in the first place — this
// override exists purely so the *link itself* can never be the thing that
// breaks the app on an older OS.
//
// Every other framework this crate (transitively, via `objc2-core-media`/
// `objc2-core-audio-types`/`dispatch2`/`block2`/Task 1's `objc2-app-kit`/
// `objc2-core-audio`/`objc2-core-graphics`) links predates macOS 11 and is
// left as an ordinary hard link, unchanged.
#[cfg(target_os = "macos")]
fn weak_link_macos_13_only_frameworks() {
  println!("cargo:rustc-link-arg=-weak_framework");
  println!("cargo:rustc-link-arg=ScreenCaptureKit");
}

#[cfg(not(target_os = "macos"))]
fn weak_link_macos_13_only_frameworks() {}

fn main() {
  weak_link_macos_13_only_frameworks();

  let attributes =
    tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS));
  tauri_build::try_build(attributes).expect("failed to run tauri-build");
}
