// Stage 5 Task 2 follow-up: an app-level ACL manifest. Without this,
// `tauri-build` never generates any permissions for this crate's own
// `#[tauri::command]`s (only for plugins) — and per Tauri's own IPC
// dispatch (`Webview::on_message`), a *local* invoke of a non-plugin
// command is only ACL-checked at all `if has_app_acl_manifest`. With no
// app manifest, that condition is false, so every app command was
// reachable from *any* window regardless of `capabilities/*.json`'s
// `windows` list — confirmed by reading tauri's own
// `crates/tauri/src/webview/mod.rs` dispatch code. `AppManifest::commands`
// below autogenerates an `allow-$command`/`deny-$command` permission pair
// per listed command (identifiers use hyphens even though the commands
// themselves are snake_case — e.g. `popup_start` becomes
// `allow-popup-start`), written to `./permissions/autogenerated/` (that
// directory is gitignored — see src-tauri/.gitignore — since it's fully
// derived from the list below, the same "generated is not source" treatment
// already given to `/gen/schemas`). `capabilities/default.json` (main
// window) and `capabilities/popup.json` (the meeting-popup window) then
// each opt into only the specific `allow-*` permissions they actually need.
//
// This list must be kept in sync with `lib.rs`'s `tauri::generate_handler!`
// list by hand — there's no compile-time link between the two (a command
// missing from here is simply unreachable from every window once this
// manifest exists at all, which would surface immediately as a broken
// invoke in every affected view, not silently).
const APP_COMMANDS: &[&str] = &[
  "hardware_info",
  "list_models",
  "recommended_models",
  "list_notes",
  "get_note",
  "search_notes",
  "rename_note",
  "toggle_action_item",
  "summarize_note",
  "ask_note",
  "delete_note",
  "storage_stats",
  "reveal_note",
  "get_settings",
  "set_settings",
  "download_model",
  "cancel_download",
  "delete_model",
  "start_recording",
  "pause_recording",
  "resume_recording",
  "stop_recording",
  "popup_start",
  "popup_dismiss",
  "sys_audio_status",
  "request_sys_audio_permission",
];

fn main() {
  let attributes =
    tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS));
  tauri_build::try_build(attributes).expect("failed to run tauri-build");
}
